### ISSUE TITLE
Fix scrolling stuttering in demo

### ISSUE THREAD

**Issue by a-ignatov-parc** [jwarning/react-scrollable-list#1]
Added `pointer-events: none;` to elements with class name `react-scrollable-list-item`. This will fix scrolling stuttering

Before:
https://cloudup.com/inrKc6ia5SH

After: 
https://cloudup.com/iy-cx3r2Dyk

**Comment by jwarning** [comment]
@a-ignatov-parc hey, sorry I never responded to this. It seems Github never notified me! I'll have a look and make the change soon.
