### ISSUE TITLE
How to add color in background and how to remove scrolling bar?

### ISSUE THREAD

**Issue by OmkarAcharekar** [jwarning/react-scrollable-list#10]
I want to add color in the background in  this white small area...and also want to remove the scrolling bar that appears
besides ....Is there any way to do so? If not can we add color to it?

![2022-03-19 (10)_LI](https://user-images.githubusercontent.com/78009952/159117874-bd4fcec8-6534-4497-bf9a-94d7b2dd740a.jpg)

This is an amazing library.....

**Comment by jwarning** [comment]
Thank you Omkar!

It looks like you just need to update the CSS styling a bit to achieve the result you are after. If you have a padding or margin set around the elements in the list then just set the background colour of the container itself to be the same as the black you have. You may need to paste an example of how you're styling it for me to know which properties to set.

In terms of the scrollbar that appears on the list, this is simply based on the browser you are using. If your page is loaded on a mobile device for example you won't see those big scroll bars anyway. You could use CSS to hide the scrollbars on a PC browser too but I wouldn't recommend that as it can cause issues. If your app is meant to run on a phone browser then I wouldn't worry about the scrollbars as they won't show when you look at the site on the phone itself.
