### ISSUE TITLE
New items aren't rendered while scrolling

### ISSUE THREAD

**Issue by bandtank** [jwarning/react-scrollable-list#13]
Here is my code:
```
import ReactScrollableList from 'react-scrollable-list';

let listItems = []
for (let i = 0; i < 10000; i++) {
  listItems.push({ id: i, content: <div>List Item {i}</div>})
}

function App() {
  return (
    <ReactScrollableList
      listItems={listItems}
    />
  );

}
export default App;
```

The page renders with 10 visible elements and it scrolls as expected, but new items do not render.

![image](https://user-images.githubusercontent.com/1170415/187572154-8313fbdc-83a0-4179-80b6-c5edbbd3f84e.png)

![image](https://user-images.githubusercontent.com/1170415/187572170-0eb04380-9a00-4cf1-ae25-dd0262c3a165.png)

What am I doing wrong? The heightOfItem property doesn't seem to do anything either. No matter what I set it to, the height of the elements stays the same.

```
$ npm --version
6.14.5
$ node --version
v14.4.0
```

**Comment by jwarning** [comment]
Hi there, I have a suspicion it might be due to you missing the `heightOfItem={...}` property on the `ReactScrollableList` component. Have a look at the example on the README as it has a working example with an explanation of the props there. Hope that helps!

**Comment by bandtank** [comment]
The code doesn't work with React 18. I copied your code into index.js with no changes and it didn't work.

```
[webpack-dev-server] Server started: Hot Module Replacement enabled, Live Reloading enabled, Progress disabled, Overlay enabled.
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
render @ react-dom.development.js:29670
./src/index.js @ index.js:10
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
react-dom.development.js:29674 Uncaught Error: Target container is not a DOM element.
    at Object.render (react-dom.development.js:29674:1)
    at ./src/index.js (index.js:10:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1
```

**Comment by jwarning** [comment]
In my example code I have this snippet:

```ReactDOM.render(
  <ReactScrollableList
    listItems={listItems}
    heightOfItem={30}
    maxItemsToRender={20}
    style={{ color: '#333' }}
  />,
  document.getElementById('app')
)
```

which will try and mount the element on a div with the id `app`. Does this exist in your example? If not that may explain the error above.

If the `heightOfItem` property was not working for you is it possible that some other css style you have is overriding it?
