### ISSUE TITLE
Persist current scroll position

### ISSUE THREAD

**Issue by Mattijah** [jwarning/react-scrollable-list#18]
Is there a way to persist the current scroll position upon refresh/update? Currently, as the data are being refreshed every couple of seconds the list becomes un-scrollable as it keeps constantly jumping to the top. Thanks!

**Comment by jwarning** [comment]
Hmm, I'm not sure if there is a reliable enough way, as it depends on whether the items you were scrolled to still exist in the list and whether or not the total length changes.

Does the list have to be refreshed every few seconds? Changing the items so frequently might mean that you need a different way to navigate the data.

**Comment by Mattijah** [comment]
> as it depends on whether the items you were scrolled to still exist in the list and whether or not the total length changes.

They do and there can only be more of them, but even if this wasn't the case it would still work ok.

> Does the list have to be refreshed every few seconds?

The list is used in a game where it's important to keep the data current and up to date, so frequent refreshes are crucial. For now I've moved away from `react-scrollable-list` and I'm simply just persisting `scrollTop` before a refresh happens.
