### ISSUE TITLE
.react-scrollable-list dynamic set css

### ISSUE THREAD

**Issue by arpecop** [jwarning/react-scrollable-list#4]
Is there any way to change the height of .react-scrollable-list inside react code , the example is with container which got fixed dimensions 
Thanks

**Comment by jwarning** [comment]
Hey, the container with the `.react-scrollable-list` class can simply be accessed like a normal DOM node within your code. You could either control its size through CSS style changes, or you could set it using the normal JS API for DOM nodes, e.g. `el.style.height = '100px'` or similar. Hopefully that helps!

**Comment by jwarning** [comment]
An example could be something like
```javascript
let customHeight = 500

<div style={{ height: customHeight }}>
  <ReactScrollableList
    listItems=[...]
    heightOfItem={30}
    maxItemsToRender={50}
  />
</div>
```

**Comment by arpecop** [comment]
Thanks for the reply,
Definitely doing something wrong here, when I define the wrapping div it starts to display empty items (not rendering) after first few , when the css rules are in the static file like so: 
`
.react-scrollable-list {
    max-height: 400px;
    overflow: auto;
 
}`

it works great, I am thinking this ReactScrollableList should be supporting style, because in the example it styles the parent div , not the .react-scrollable-list class itself

**Comment by jwarning** [comment]
Yeah I agree that having support for inline styling might be good, so I've added an optional style prop to the list item itself such that you can pass through any styling with JS if you'd like. Just as a note, if you're seeing a bunch of empty space after the items, you may have not set the `maxItemsToRender` prop high enough, as it only defaults to 50. Version 1.2.0 should have the change you need now.
