### ISSUE TITLE
Examples do not match what needs to be imported

### ISSUE THREAD

**Issue by josephthweatt** [jwarning/react-scrollable-list#6]
The README and the example **app.js** are using a component called ReactScrollableList, but it seems like ScrollableList is what needs to be imported. Do the examples need to be changed out?

**Comment by jwarning** [comment]
I see what you mean, however due to the way ES6 import/exports work, the class that is exported is the default export which means that you can import it by the name of your choice, so: 
```javascript
import ReactScrollableList from 'react-scrollable-list'
// or
import ScrollableList from 'react-scrollable-list'
// or
import foo from 'react-scrollable-list'
```
are all valid ways of importing the module. Hope that helps!
