### ISSUE TITLE
Warnings when using strict mode

### ISSUE THREAD

**Issue by lwoydziak** [jwarning/react-scrollable-list#7]
Warning: A string ref, "list", has been found within a strict mode tree. String refs are a source of potential bugs and should be avoided. We recommend using useRef() or createRef() instead. Learn more about using refs safely here: https://fb.me/react-strict-mode-string-ref.

See index.js:22-35

```
componentDidMount() {
    this.refs.list.addEventListener('scroll', this.updateScrollPosition)
  }
  componentWillUnmount() {
    this.refs.list.removeEventListener('scroll', this.updateScrollPosition)
  }
  updateScrollPosition() {
    const newScrollPosition = this.refs.list.scrollTop / this.props.heightOfItem
    const difference = Math.abs(this.state.scrollPosition - newScrollPosition)

    if (difference >= this.props.maxItemsToRender / 5) {
      this.setState({ scrollPosition: newScrollPosition })
    }
  }
```

**Comment by jwarning** [comment]
Hi @lwoydziak , I've updated the component to use callback refs instead of the older string refs now, so that warning should go away. I've pushed a new version 1.3.0 with the change in it.
