### ISSUE TITLE
prop-types is not in your dependencies

### ISSUE THREAD

**Issue by tangshuang** [jwarning/react-scrollable-list#8]
You required prop-types, but not write it in package.json dependencies

**Comment by jwarning** [comment]
Hmm, it is in the dev dependencies section of the package.json already. Is it throwing a warning or an error for you? Perhaps it needs to be in peer dependencies too.

**Comment by tangshuang** [comment]
So you mean developers should install prop-types by him/herself?

**Comment by jwarning** [comment]
I have added prop-types to the npm dependencies in the latest version now as that should be the simplest way to solve the issue.
