### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by rjworks** [jwarning/react-scrollable-list#9]
error
```
2index.js:1 Warning: Encountered two children with the same key, `list-item-undefined`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at div
    at ScrollableList (http://localhost:3000/static/js/vendors~main.chunk.js:60583:5)
    at div
    at Home
    at App
```

```
 const courseList = ['111', '121', ' 222'];
<ReactScrollableList
                listItems={courseList}
                heightOfItem={30}
                maxItemsToRender={50}
                style={{ color: '#333' }}``
```

**Comment by jwarning** [comment]
Hey there, it looks like you are passing your data in as a simple array instead of keyed objects.

In the docs the example is as follows:

```
{
  id: 'a unique identifier',
  content: 'the content to display inside the div'
}
```

whereas you are passing `['111', '121', ' 222']` as your data.

If you change your data to match this format, eg.

```
const courseList = [{ id: '111', content: '111'}, { id: '121', content: '121'}, { id: '222', content: '222'}]
```

then it should work! hope that helps

**Comment by rjworks** [comment]
> Hey there, it looks like you are passing your data in as a simple array instead of keyed objects.
> 
> In the docs the example is as follows:
> 
> ```
> {
>   id: 'a unique identifier',
>   content: 'the content to display inside the div'
> }
> ```
> 
> whereas you are passing `['111', '121', ' 222']` as your data.
> 
> If you change your data to match this format, eg.
> 
> ```
> const courseList = [{ id: '111', content: '111'}, { id: '121', content: '121'}, { id: '222', content: '222'}]
> ```
> 
> then it should work! hope that helps

Thank you

**Comment by rjworks** [comment]
Am I able to have separate boxes for each content?

![image](https://user-images.githubusercontent.com/46464980/116852066-e5a01700-abb0-11eb-9805-eac35cd24115.png)

like this 
![image](https://user-images.githubusercontent.com/46464980/116852482-9efeec80-abb1-11eb-9c56-6717e4ee54e9.png)

**Comment by jwarning** [comment]
You can if you style the elements to look like that. The class `.react-scrollable-list` is for the list container div and `.react-scrollable-list-item` is for each individual element div. Hope that helps!
